steps:
    # Build and tag image
-   name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '.']

    # Push the container image to Container Registry
-   name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME']

    # Deploy container image to Cloud Run
-   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'discogs-notifier', 
    '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME', 
    '--region', 'us-central1', 
    '--platform', 'managed',
    '--set-env-vars', 'DISCOGS_USERNAME=$$_DISCOGS_USERNAME',
    '--set-env-vars', 'USER_EMAIL=$$_USER_EMAIL',
    '--set-env-vars', 'DISCOGS_TOKEN=$$DISCOGS_TOKEN',
    '--set-env-vars', 'SMTP_ADDRESS=$$_SMTP_ADDRESS',
    '--set-env-vars', 'SMTP_USERNAME=$$SMTP_USERNAME',
    '--set-env-vars', 'SMTP_PASSWORD=$$SMTP_PASSWORD',
    '--set-env-vars', '"VERBOSE=true"',
    '--set-env-vars', '"PORT=8080"'
    ]
    secretEnv: ['DISCOGS_TOKEN', 'SMTP_USERNAME', 'SMTP_PASSWORD']

images:
    - gcr.io/$PROJECT_ID/$REPO_NAME    
    
availableSecrets:
    secretManager:
        - versionName: projects/221674413825/secrets/DISCOGS_TOKEN/versions/1
          env: 'DISCOGS_TOKEN'
        - versionName: projects/221674413825/secrets/SMTP_USERNAME/versions/1
          env: 'SMTP_USERNAME'
        - versionName: projects/221674413825/secrets/SMTP_PASSWORD/versions/1
          env: 'SMTP_PASSWORD'
